(()=>{
const view=document.getElementById("view");
const base=()=>{if(location.hostname==="tauri.localhost"||location.hostname.endsWith(".tauri.localhost"))return "http://127.0.0.1:41800";if(location.protocol==="http:"||location.protocol==="https:")return location.origin;return "http://127.0.0.1:41800"};
const get=async p=>{const r=await fetch(base()+p,{cache:"no-store"});const t=await r.text();if(!r.ok)throw Error(t||("HTTP "+r.status));return JSON.parse(t)};
const post=async(p,b)=>{const r=await fetch(base()+p,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});const t=await r.text();if(!r.ok)throw Error(t||("HTTP "+r.status));return JSON.parse(t)};
const esc=x=>String(x??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const fmt=n=>{const raw=String(n??0);if(!/^\\d+(?:\\.\\d+)?$/.test(raw))return "0 ONECOIN";const [whole,fraction=""]=raw.split(".");const grouped=whole.replace(/\\B(?=(\\d{3})+(?!\\d))/g,",");const decimals=fraction.replace(/0+$/,"");return grouped+(decimals?"."+decimals:"")+" ONECOIN"};
let offers=[];try{const cached=JSON.parse(localStorage.getItem("awenet.onecoin.offers")||"[]");if(Array.isArray(cached))offers=cached}catch(_){}
const tiers=[["FREE","0 contribution","20 GB · 1 CPU · 1 GB RAM VPS","No contribution reward"],["BASIC","Any verified resource","Your resource + 20 GB · 2 CPU · 4 GB RAM · 24/7","10 ONECOIN/month minimum"],["NET+","100 GB · 4 CPU · 8 GB RAM · 1 TB+","Your resource + 30 GB · 2 CPU · 8 GB RAM · 24/7","40–50 ONECOIN/month minimum"],["NET PRO","1 TB+ · 8 CPU · GPU · 16 GB+ RAM","Your resource + NET-equivalent resource","Usage-based reward"],["NET ULTRA","Multiple nodes/servers","Data-centre capabilities","Usage + contribution"],["PRO","100+ servers","Large infrastructure governance","Usage + contribution"],["DATA GROUP","100,000+ resource units","Full Data Group management","Usage + contribution"],["CENTRE GROUP","1,000,000+ resource units","Full Centre Group management","Usage + contribution"],["AWENET USER","Network governance","Protocol governance; no infinite balance/resources","Governance-controlled issuance"]];
function render(){
view.innerHTML="<div class=\"onecoin-hero\"><div><div class=\"eyebrow\">ONEBANK / ONECOIN</div><h1>Network economy</h1><p>Wallet balances, signed local exchange offers and contribution estimates. Network payments still require consensus finalization.</p></div><div class=\"coin-orb\">1C</div></div>"+
"<div class=\"onecoin-grid\"><div class=\"card onecoin-stat\"><div class=\"metric-label\">Wallet</div><div id=\"ocBalance\" class=\"metric\">Connecting…</div><div id=\"ocOwner\" class=\"muted\">Loading AWE ID</div><div id=\"ocPending\" class=\"muted\">Checking pending transfers…</div></div><div class=\"card onecoin-stat\"><div class=\"metric-label\">Tier</div><div id=\"ocTier\" class=\"metric\">Loading…</div><div id=\"ocContribution\" class=\"muted\">Declared resource contribution — not verified</div></div><div class=\"card onecoin-stat\"><div class=\"metric-label\">ONEBANK fee</div><div id=\"ocFee\" class=\"metric\">1%</div><div class=\"muted\">Configurable 0–5%</div></div><div class=\"card onecoin-stat\"><div class=\"metric-label\">Exchange</div><div class=\"metric\">P2P</div><div class=\"muted\">External fiat settlement rail</div></div></div>"+
"<div class=\"onecoin-tabs\"><button class=\"oc-tab active\" data-tab=\"wallet\">Wallet</button><button class=\"oc-tab\" data-tab=\"exchange\">Exchange</button><button class=\"oc-tab\" data-tab=\"rewards\">Rewards</button><button class=\"oc-tab\" data-tab=\"tiers\">Tiers</button></div>"+
"<section id=\"oc-wallet\" class=\"oc-panel\"><div class=\"section panel\"><div class=\"section-head\"><h2>Wallet</h2></div><div class=\"peer-form\"><input id=\"ocRecipient\" placeholder=\"Recipient AWE ID (64 hex)\"><input id=\"ocAmount\" type=\"number\" min=\"0.000000000000000001\" step=\"0.000000000000000001\" placeholder=\"ONECOIN amount\"><input id=\"ocMemo\" placeholder=\"Memo\"><button class=\"secondary\" id=\"ocCopyOwner\" type=\"button\">Copy receive AWEID</button><button class=\"primary\" id=\"ocSend\">Send ONECOIN</button></div><div id=\"ocWalletState\" class=\"notice\">Identity secret files are local and sensitive. Keep them private; transfers must be finalized by network consensus.</div></div></section>"+
"<section id=\"oc-exchange\" class=\"oc-panel\" hidden><div class=\"section panel\"><div class=\"section-head\"><h2>Create P2P offer</h2></div><div class=\"peer-form\"><select id=\"ocSide\"><option value=\"sell\">Sell ONECOIN</option><option value=\"buy\">Buy ONECOIN</option></select><input id=\"ocOfferAmount\" type=\"number\" min=\"0.000000000000000001\" step=\"0.000000000000000001\" placeholder=\"ONECOIN amount\"><input id=\"ocPrice\" type=\"number\" min=\"0.01\" step=\"0.01\" placeholder=\"Fiat price / coin\"><select id=\"ocCurrency\"><option>USD</option><option>EUR</option><option>AMD</option><option>GBP</option></select><select id=\"ocRail\"><option>ExternalPayment</option><option>BankTransfer</option><option>Cash</option></select><button class=\"primary\" id=\"ocOffer\">Publish offer</button></div><div id=\"ocExchangeState\" class=\"notice\">ONEBANK records the ONECOIN order; actual fiat transfer must use the selected external payment rail.</div></div><div class=\"section panel\"><div class=\"section-head\"><h2>Offers</h2></div><div id=\"ocOffers\"></div></div></section>"+
"<section id=\"oc-rewards\" class=\"oc-panel\" hidden><div class=\"section panel\"><div class=\"section-head\"><h2>Contribution rewards</h2></div><div class=\"notice\">Reward = verified resource contribution + availability + actual utilization. BASIC minimum: 10 ONECOIN/month. NET+ minimum: 40–50 ONECOIN/month.</div><div class=\"onecoin-form-grid\"><input id=\"ocStorage\" type=\"number\" placeholder=\"Storage GB\"><input id=\"ocCpu\" type=\"number\" placeholder=\"CPU cores\"><input id=\"ocRam\" type=\"number\" placeholder=\"RAM GB\"><input id=\"ocGpu\" type=\"number\" placeholder=\"GPU units\"><input id=\"ocBandwidth\" type=\"number\" placeholder=\"Bandwidth TB/day\"><input id=\"ocUsage\" type=\"number\" min=\"0\" max=\"100\" placeholder=\"Utilization %\"></div><button class=\"primary\" id=\"ocCalc\">Calculate estimate</button><div id=\"ocCalcState\" class=\"notice\">Informational estimate until a signed contribution receipt is accepted.</div></div></section>"+
"<section id=\"oc-tiers\" class=\"oc-panel\" hidden><div class=\"section panel\"><div class=\"section-head\"><h2>Contribution hierarchy</h2></div><div class=\"tier-list\">"+tiers.map(t=>"<div class=\"tier-row\"><div><b>"+esc(t[0])+"</b><small>"+esc(t[1])+"</small></div><span>"+esc(t[2])+"</span><strong>"+esc(t[3])+"</strong></div>").join("")+"</div></div></section>";
bind();loadWallet();loadOffers();renderOffers();
}
function bind(){
document.querySelectorAll(".oc-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".oc-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".oc-panel").forEach(x=>x.hidden=true);document.getElementById("oc-"+b.dataset.tab).hidden=false});
document.getElementById("ocCopyOwner").onclick=async()=>{const s=document.getElementById("ocWalletState"),address=document.getElementById("ocOwner").textContent.trim();if(!/^[0-9a-f]{64}$/i.test(address)){s.textContent="A valid receive AWEID is not available yet.";return}try{await navigator.clipboard.writeText(address);s.textContent="Receive AWEID copied to clipboard."}catch(_){s.textContent="Clipboard access is unavailable. Select and copy the AWEID shown above."}};
document.getElementById("ocSend").onclick=async()=>{const s=document.getElementById("ocWalletState"),recipient=document.getElementById("ocRecipient").value.trim(),amountRaw=document.getElementById("ocAmount").value.trim(),amount=Number(amountRaw);if(!recipient||!Number.isFinite(amount)||amount<=0){s.textContent="Recipient and positive amount are required.";return}if(!/^\\d+(?:\\.\\d{1,18})?$/.test(amountRaw)){s.textContent="Use a decimal amount with at most 18 decimal places.";return}try{const r=await post("/api/onebank/wallet/send",{recipient,amount_coins:amountRaw,memo:document.getElementById("ocMemo").value.trim()});s.textContent=r.recipient_pending?"Transfer saved for retry; awaiting recipient delivery: "+(r.tx_id||""):r.recipient_delivered?"Recipient wallet confirmed transfer: "+(r.tx_id||""):"Transfer accepted: "+(r.tx_id||r.error||"");loadWallet()}catch(e){s.textContent="Transfer rejected/backend unavailable: "+e.message}};
document.getElementById("ocOffer").onclick=async()=>{const s=document.getElementById("ocExchangeState"),amountRaw=document.getElementById("ocOfferAmount").value.trim(),priceRaw=document.getElementById("ocPrice").value.trim(),amount=Number(amountRaw),price=Number(priceRaw);if(!/^\d+(?:\.\d{1,18})?$/.test(amountRaw)||!Number.isFinite(amount)||amount<=0){s.textContent="Enter a positive amount with at most 18 decimal places.";return}if(!/^\d+(?:\.\d{1,2})?$/.test(priceRaw)||!Number.isFinite(price)||price<=0){s.textContent="Enter a positive fiat price with at most 2 decimal places.";return}const o={id:crypto.randomUUID(),side:document.getElementById("ocSide").value,amount:amountRaw,price:priceRaw,currency:document.getElementById("ocCurrency").value,rail:document.getElementById("ocRail").value,created_at:Date.now()};try{const r=await post("/api/onebank/exchange/offers",{offer:o});if(r.status!=="published")throw Error(r.error||"offer was rejected");if(r.offer){offers.unshift(r.offer);localStorage.setItem("awenet.onecoin.offers",JSON.stringify(offers))}s.textContent="Published and signed by this node: "+(r.offer?.id||o.id)+". Fiat settlement remains external."}catch(e){offers.unshift({...o,signature_verified:false});localStorage.setItem("awenet.onecoin.offers",JSON.stringify(offers));s.textContent="Not published to the node. Saved as a local draft: "+e.message}renderOffers()};
document.getElementById("ocCalc").onclick=async()=>{const storage=(Number(document.getElementById("ocStorage").value)||0)*1073741824,cpu=Number(document.getElementById("ocCpu").value)||0,ram=(Number(document.getElementById("ocRam").value)||0)*1073741824,gpu=Number(document.getElementById("ocGpu").value)||0,bw=(Number(document.getElementById("ocBandwidth").value)||0)*1000000000000,usage=Math.max(0,Math.min(100,Number(document.getElementById("ocUsage").value)||0));let tier="FREE";if(storage||cpu||ram||gpu||bw)tier="BASIC";if(storage>=100*1073741824&&cpu>=4&&ram>=8*1073741824&&bw>=1000000000000)tier="NET+";if(storage>=1000000000000&&cpu>=8&&ram>=16*1073741824&&gpu>=1)tier="NET PRO";const min=tier==="BASIC"?10:tier==="NET+"?45:0,score=storage/1048576+(ram/1048576)*4+cpu*1024+gpu*16384+bw/1048576,estimate=min+score*.001*(usage/100);document.getElementById("ocCalcState").textContent="Estimated tier: "+tier+" (based on declared, unverified resources). Illustrative estimate: "+estimate.toFixed(4)+" ONECOIN/month. Actual reward requires signed usage receipts.";try{await post("/api/onebank/contribution",{storage_bytes:Math.floor(storage),cpu_cores:cpu,ram_bytes:Math.floor(ram),gpu_units:gpu,bandwidth_bytes:Math.floor(bw),online_hours:0,node_count:(storage||cpu||ram||gpu||bw)?1:0,server_count:(storage||cpu||ram||gpu||bw)?1:0,uptime_bps:0,utilization_bps:Math.round(usage*100)});loadWallet()}catch(_){}};
}
async function loadWallet(){try{const d=await get("/api/onebank/wallet");document.getElementById("ocBalance").textContent=fmt(d.balance_coins_exact??d.balance_coins??0);document.getElementById("ocOwner").textContent=d.awe_id||"AWE ID unavailable";document.getElementById("ocTier").textContent=d.tier||"FREE";document.getElementById("ocContribution").textContent=d.resource_score!=null?"Resource score · "+d.resource_score:"Contribution unavailable";document.getElementById("ocFee").textContent=((d.fee_bps||100)/100)+"%";document.getElementById("ocPending").textContent=d.pending_transfers?("Pending delivery: "+d.pending_transfers):"No pending transfers"}catch(_){document.getElementById("ocBalance").textContent="Ledger offline";document.getElementById("ocOwner").textContent="Start an ONEBANK-enabled node";document.getElementById("ocTier").textContent="FREE"}}
async function loadOffers(){try{const remote=await get("/api/onebank/exchange/offers");if(Array.isArray(remote)){offers=remote;localStorage.setItem("awenet.onecoin.offers",JSON.stringify(remote));renderOffers()}}catch(_){}}
function renderOffers(){const b=document.getElementById("ocOffers");if(!b)return;b.innerHTML=offers.length?offers.map(o=>"<div class=\"offer-row\"><b>"+esc(o.side.toUpperCase())+"</b><span>"+esc(o.amount)+" ONECOIN</span><span>"+esc(o.price)+" "+esc(o.currency)+"/coin</span><span>"+esc(o.rail)+"</span><small>"+(o.signature_verified?"Signed by local node · external settlement":"local draft — not published")+"</small></div>").join(""):"<div class=\"empty\">No local offers. Connected ONEBANK offers appear here.</div>"}
document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>{if(n.dataset.view==="onecoin"){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===n));document.getElementById("pageTitle").textContent="ONECOIN";render()}}));
})();