[package]
name = "awep2p-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "awep2p_core"
crate-type = ["rlib", "cdylib"]

[dependencies]
libc = { workspace = true, optional = false }
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
rand.workspace = true
rand_core.workspace = true
ed25519-dalek.workspace = true
argon2.workspace = true
chacha20poly1305.workspace = true
zeroize.workspace = true
hex.workspace = true
reed-solomon-erasure.workspace = true
blake3.workspace = true
hkdf.workspace = true
x25519-dalek.workspace = true
tokio.workspace = true

[target.'cfg(windows)'.dependencies]
winapi = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
