name: AWEp2P Core

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'core/**'
      - '.github/workflows/core.yml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'core/**'
      - '.github/workflows/core.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo check --workspace --all-targets
      - run: cargo test --workspace --all-targets
      - run: cargo clippy --workspace --all-targets -- -D warnings
